### PR TITLE
Added hidelinks flag to hyperref usage to links are hidden

### PR DESCRIPTION
**Pull request by Jdban**
Some PDF readers make links make your paper look awful with these big ugly boxes around them. When I had my paper formatting reviewed, they told me to remove the usage of yellow and green and blue coloring from my paper which I was unaware of, and this was the cause. 

I enabled the hidelinks flag in the hyperref package in order to stop this from happening ([link here](http://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks)).

Here is what my paper looked like before and after in one offending pdf reader:

Before:

After:

### CODE REVIEW

**Comment by AndrewGuenther** [comment]
Does this disable links altogether? Or just remove the boxes?

**Comment by Jdban** [comment]
It just removes the horrifically ugly boxes, the links still work. Documentation here: http://mirrors.concertpass.com/tex-archive/macros/latex/contrib/hyperref/doc/manual.pdf

**Comment by AndrewGuenther** [comment]
@Jdban cool, can you rebase and I'll merge?

**Comment by AndrewGuenther** [comment]
Sorry for the delay, one more time?

**Comment by AndrewGuenther** [comment]
It is really annoying that Github doesn't notify when a rebase is done. No wonder I missed it the first time.

**Comment by Jdban** [comment]
Oh that's annoying. Good to know.

**Pull request merged**
